 pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>cd 
..

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd ..

C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>venv_name\Scripts\a
ctivate.bat

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>venv_name\Scripts\activate.bat

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>cd ..  

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class2  

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd Django-Class-2

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull https://github.com/akanshabaishwade/Django-Class-2.git
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull https://github.com/akanshabaishwade/Django-Class-2.git
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>cd ..                                                      
     
(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd .. 

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class     

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>cd ..  

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class2  

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd Django-Class-2

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pullhttps://github.com/akanshabaishwade/Django-Class-2.git
git: 'pullhttps://github.com/akanshabaishwade/Django-Class-2.git' is not a git command. See 'git --help'.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull https://github.com/akanshabaishwade/Django-Class-2.git 
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>
 *  History restored 

Microsoft Windows [Version 10.0.22631.4169]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class2

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd Django-Class-2

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git
 pull https://github.com/akanshabaishwade/Django-Class-2.git
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull https://github.com/akanshabaishwade/Django-Class-2.git        
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull https://github.com/akanshabaishwade/Django-Class-2.git        
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>   
 *  History restored 

Microsoft Windows [Version 10.0.22631.4169]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class2

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd Django-Class-2

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git
 pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>ven
v_name\Scripts\activate.bat
The system cannot find the path specified.

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>cd 
..

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd ..

C:\Users\Asus\Desktop\ITC EDUCATION>venv_name\Scripts\activate.bat
The system cannot find the path specified.

C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class

C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>venv_name\Scripts\activate.bat

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>cd coll
ege

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\college>cd ..

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>cd ..  

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>Django-Class2
'Django-Class2' is not recognized as an internal or external command,
operable program or batch file.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class2 

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd Django-Class-2

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2\Django-Class-2>cd ..             

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class2>cd ..

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION>cd Django-Class 

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class>cd college


(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\college> V
(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\college>python3 manage.py shell
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\college>python manage.py runserver 
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 14, 2024 - 23:06:53
Django version 5.1, using settings 'college.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.


(venv_name) C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\college>python manage.py shell     
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information. 
(InteractiveConsole)
>>> from django.contrib.auth.models import User
>>> from appname.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'appname'
>>> from arts.models import *    
>>> Student.objects.all()
<QuerySet [<Student: komal kamble>, <Student: kaveri kurade>, <Student: Jane Smith>]>
>>> student = Student.objects.get(id=1)
>>>
>>> print(student) 
komal kamble
>>> student = Student.objects.get(age=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
arts.models.Student.DoesNotExist: Student matching query does not exist.
>>> student = Student.objects.get(age=30) 
>>> print(student) 
komal kamble
>>> student = Student.objects.get(age=30)
>>> print(student)                        
komal kamble
>>> Student.objects.filter(age__lt=25)
<QuerySet [<Student: kaveri kurade>, <Student: Jane Smith>]>
>>> filter = Student.objects.filter(field_name)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'field_name' is not defined
>>> filter = Student.objects.filter(first_name) 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'first_name' is not defined
>>> filter = Student.objects.filter(age)        
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'age' is not defined
>>> filter = Student.objects.filter(field_name)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'field_name' is not defined
>>>
KeyboardInterrupt
>>> from django.db.models import Avg
>>> Student.objects.filter(age__lt=25)
<QuerySet [<Student: kaveri kurade>, <Student: Jane Smith>]>
>>> Student.objects.get(name='ram',).filter(age=1).delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q      
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q     
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: age, date_of_birth, first_name, id, last_name       
>>> Student.objects.get(first_name='ram',).filter(age=1).delete() 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
arts.models.Student.DoesNotExist: Student matching query does not exist.
>>> filter = Student.objects.filter(field_name)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'field_name' is not defined
>>> filter = Student.objects.filter(first_name) 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'first_name' is not defined
>>> Student.objects.filter(first_name)          
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'first_name' is not defined
>>> average_age = Student.objects.aggregate(Avg('age'))
>>> print(average_age) 
{'age__avg': 24.0}
>>> from django.db.models import Count
>>> from django.db.models import Count
>>> tudents = models.ManyToManyField(Student, related_name='courses')
>>> students = models.ManyToManyField(Student, related_name='courses') 
>>> print(students) 
<django.db.models.fields.related.ManyToManyField>
>>> students_with_course_count = Student.objects.annotate(course_count=Count('courses')) #Todo
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1630, in annotate       
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1680, in _annotate      
    clone.query.add_annotation(
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1194, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\expressions.py", line 1073, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\expressions.py", line 895, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2010, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1863, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'courses' into field. Choices are: age, date_of_birth, first_name, id, last_name    
>>> students_with_course_count = Student.objects.annotate(course_count=Count('courses'))      
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1630, in annotate       
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1680, in _annotate      
    clone.query.add_annotation(
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1194, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\aggregates.py", line 63, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\expressions.py", line 1073, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\expressions.py", line 895, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2010, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1863, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'courses' into field. Choices are: age, date_of_birth, first_name, id, last_name    
>>> students = Student.objects.order_by('age')
>>> print(students)                                                    
<QuerySet [<Student: kaveri kurade>, <Student: Jane Smith>, <Student: komal kamble>]>
>>> students_desc = Student.objects.order_by('-age')
>>> print(students_desc) 
<QuerySet [<Student: komal kamble>, <Student: Jane Smith>, <Student: kaveri kurade>]>
>>> duplicate remove = Student.objects.distinct()
  File "<console>", line 1
    duplicate remove = Student.objects.distinct()
              ^^^^^^
SyntaxError: invalid syntax
>>> students_info = Student.objects.values('name', 'age')
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2195, in add_fields 
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1863, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: age, date_of_birth, first_name, id, last_name       

During handling of the above exception, another exception occurred:    

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1360, in values
    clone = self._values(*fields, **expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1355, in _values        
    clone.query.set_values(fields)
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2500, in set_values 
    self.add_fields(field_names, True)
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2223, in add_fields 
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: age, date_of_birth, first_name, id, last_name       
>>> students_info = Student.objects.values('first_name', 'age') 
>>> print(students_info)                                        
<QuerySet [{'first_name': 'komal', 'age': 30}, {'first_name': 'kaveri', 'age': 20}, {'first_name': 'Jane', 'age': 22}]>
>>> student_names = Student.objects.values_list('name', flat=True)
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2195, in add_fields 
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1863, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: age, date_of_birth, first_name, id, last_name       

During handling of the above exception, another exception occurred:    

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method 
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1392, in values_list    
    clone = self._values(*_fields, **expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\query.py", line 1355, in _values        
    clone.query.set_values(fields)
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2500, in set_values 
    self.add_fields(field_names, True)
  File "C:\Users\Asus\Desktop\ITC EDUCATION\Django-Class\venv_name\Lib\site-packages\django\db\models\sql\query.py", line 2223, in add_fields 
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: age, date_of_birth, first_name, id, last_name       
>>> student_names = Student.objects.values_list('first_name', flat=True) 
>>> print(students_names)                                              
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'students_names' is not defined. Did you mean: 'student_names'?
>>> print(student_names)                                               
<QuerySet ['komal', 'kaveri', 'Jane']>
>>> has_students = Student.objects.filter(age=20).exists()
>>> has_students = Student.objects.filter(age=20).exists()
>>> print(has_students)  
True
>>> student_count = Student.objects.filter(age=20).count()
>>> print(students_count) 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'students_count' is not defined. Did you mean: 'student_count'?
>>> print(student_count)  
1
>>> first_student = Student.objects.first()
>>> print(first_student) 
komal kamble
>>> last_student = Student.objects.last()
>>> print(last_student)  
Jane Smith
>>>